services:
  php-apache:
    build: .
    container_name: gerenciador_apd
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
