services:
  php-apache:
    build: .
    container_name: php-container
    ports:
      - "3300:80" # Mapeia a porta 80 do container para a porta 8080 do host
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
